linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused

run:
  timeout: 2m
  issues-exit-code: 1

linters-settings:
  errcheck:
    check-type-assertions: true
