// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"Gault/pkg/logger"
)

// Injectors from wire.go:

func InitializeLogger() error {
	error2 := logger.NewLogger()
	return error2
}
