name: Build CLI

on:
  pull_request:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install protoc-gen-go, protoc-gen-go-grpc, mockgen and wire
        run: |
          go install github.com/bufbuild/buf/cmd/buf@latest
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest
          go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
          go install github.com/golang/mock/mockgen@latest
          go install github.com/google/wire/cmd/wire@latest
          go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
          go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Generate protobuf
        run: |
          buf lint
          buf generate --path api/proto/v1

      - name: Generate mockgen
        run: |
          mockgen -source=./internal/db/repository.go -destination=./gen/go/db/repository_mock.go -package=db 
          sqlc generate

      - name: Generate wire
        run: |
          cd internal/injector && wire

      - name: Build
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)

          echo "VERSION=$VERSION"
          echo "BUILD_DATE=$BUILD_DATE"

          export GOOS=${{ matrix.goos }}
          export GOARCH=${{ matrix.goarch }}

          go build -o gault-$GOOS-$GOARCH \
            -ldflags "-X main.Version=$VERSION -X main.BuildDate=$BUILD_DATE" \
            ./cmd/client/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.goos }}-${{ matrix.goarch }}
          path: gault-${{ matrix.goos }}-${{ matrix.goarch }}
