name: Linter

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install protoc-gen-go, protoc-gen-go-grpc and mockgen
        run: |
          go install github.com/bufbuild/buf/cmd/buf@latest
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest
          go install github.com/golang/mock/mockgen@latest

      - name: Generate protobuf
        run: |
          buf mod update
          buf lint
          buf generate

      - name: Generate mockgen
        run: |
          mockgen -source=./internal/db/repository.go -destination=./gen/go/db/repository_mock.go -package=db 
          mockgen -source=./gen/go/api/proto/v1/data_service_grpc.pb.go -destination=./gen/go/client/client_mock.go -package=client

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
