name: Test and Coverage

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install protoc-gen-go, protoc-gen-go-grpc, mockgen and wire
        run: |
          go install github.com/bufbuild/buf/cmd/buf@latest
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest
          go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
          go install github.com/golang/mock/mockgen@latest
          go install github.com/google/wire/cmd/wire@latest
          go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
          go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Generate protobuf
        run: |
          buf lint
          buf generate --path api/proto/v1

      - name: Generate mockgen
        run: |
          mockgen -source=./internal/db/repository.go -destination=./gen/go/db/repository_mock.go -package=db 
          sqlc generate

      - name: Generate wire
        run: |
          cd internal/injector && wire

      - name: Run tests
        run: |
          go test -covermode=atomic -coverprofile=coverage.out ./...
          grep -v "gen" coverage.out > coverage.filtered.out

      - name: Show coverage in logs
        run: go tool cover -func=coverage.filtered.out
